version: '3'
services:
  apache:
    build: api/.docker/apache
    container_name: newproject_apache
    ports:
      - "8001:80"
    volumes:
      - ./api/.docker/config/vhosts:/etc/apache2/sites-enabled
      - ./api:/var/www/html
    depends_on:
      - php
  
  php:
    build: api/.docker/php
    container_name: newproject_php
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql
  
  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: newproject_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newproject
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: newproject_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8012:80"
    links:
      - mysql
